### ISSUE TITLE
Cannot create symlink operation not permitted

### ISSUE THREAD

**Issue by bhuvi6dl** [ArchimedesPi/SageMathematics-raspi#1]
Hi,

Firstly, I'd like like to thank you for this binary. I downloaded it on my Pi and checked the md5sum and it was fine. The unzipping however is throwing lots of errors of the kind 'Cannot create symlink operation not permitted'. The process still continues and fails eventually (as it says it's failed to recover from previous errors).

I have also tried prefixing the tar command with sudo, but it hasn't helped. Also, this process is writing files to a usb drive (since my sd card is 8gb and so I am creating my sage folder on a mounted usb flash drive).

I am a novice linux user so any help will be really appreciated.

**Comment by erinzm** [comment]
I see that you closed the issue - How did you get it to work?
